### ISSUE TITLE
Investigate test_sign_in_helper_with_returning_user failures in Sauce Labs job

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bidpom#112]
test_sign_in_helper_with_returning_user fails, recently, quite a bit more in Sauce Labs than in our own infrastructure.  We should investigate why, and see what we can do about it.

https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage.saucelabs/1545/testReport/junit/tests.check_sign_in/TestSignIn/test_sign_in_helper_with_returning_user/history/

Error Message

tests/check_sign_in.py:88: in test_sign_in_helper_with_returning_user     WebDriverWait(selenium, timeout).until(lambda s: s.find_element( .venv/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/support/wait.py:80: in until     raise TimeoutException(message, screen, stacktrace) E   TimeoutException: Message:

Stacktrace

tests/check_sign_in.py:88: in test_sign_in_helper_with_returning_user
    WebDriverWait(selenium, timeout).until(lambda s: s.find_element(
.venv/lib/python2.7/site-packages/selenium-2.53.6-py2.7.egg/selenium/webdriver/support/wait.py:80: in until
    raise TimeoutException(message, screen, stacktrace)
E   TimeoutException: Message:

**Comment by stephendonner** [comment]
Update: this looks partially due to platform (timing) differences, as changing the platform for this Sauce Labs run to be Windows, from Mac, seems to have helped quite a bit:

https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/jobConfigHistory/showDiffFiles?timestamp1=2016-05-31_12-41-33&timestamp2=2016-07-05_19-15-28

I'll leave this open for further investigation, and will close if we don't see issues in a while, now that we're on Windows.

**Comment by davehunt** [comment]
Do you know if this is still happening @stephendonner? I suspect with the upcoming shutdown for Persona that we may want to just close this - what do you think?

**Comment by stephendonner** [comment]
@davehunt it still happens, but not very often.  In the last 30 runs, it didn't fail (there were 4 failures, but they were either HTTP 503 - Service Unavailable or Personatestuser-email issues).

https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage/1887/testReport/junit/tests.check_sign_in/TestSignIn/test_sign_in_helper_with_returning_user/history/?start=25

Example of it still happening: https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage/1855/testReport/tests.check_sign_in/TestSignIn/test_sign_in_helper_with_returning_user/

I'm fine with closing this, given the frequency and the impending Persona shutdown, but it's still a valid issue, so leaving opening I'd be fine with too :-)

**Comment by davehunt** [comment]
Closing as this project is no longer active.
