### ISSUE TITLE
Deactivate/decommission BIDPOM repo

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bidpom#127]
http://123done.org, http://beta.123done.org, and http://personatestuser.org are returning errors (null for verified email) + timing out, due to the official Persona.org shutdown.

Due to the above, https://webqa-ci.mozilla.com/view/BIDPOM/job/bidpom.stage/ is failing 9 out of 9 tests, now.

We should probably deactivate/decommission[0] this repo.  @davehunt thoughts?

I'd be happy to take on this work.

[0] https://wiki.mozilla.org/QA/Execution/Web_Testing/Automation/Repositories#Deactivating_a_repository

**Comment by davehunt** [comment]
I don't think we need to remove the content like we have for test repositories. Let's change the development status to indicate the package is inactive like we did for pytest-mozwebqa, and add a note to the README to indicate this project is no longer actively maintained.

**Comment by davehunt** [comment]
Fixed by #128
