### ISSUE TITLE
rework browserid popup identification

### ISSUE THREAD

**Issue by klrmn** [mozilla/bidpom#21]
from @davehunt via email:

> BIDPOM currently cycles through the open windows until it finds out with the appropriate page title. This is a little more fragile than I'd like as the page title should be able to change without affecting the tests (and the page title is different in each locale). Since https://github.com/mozilla/browserid/issues/1023 has been fixed we can improve BIDPOM by referencing the popup window by name "__persona_dialog". Leah: this would certainly be a worthwhile enhancement if you'd like to take it.

**Comment by rbillings** [comment]
Closing as Persona is being decommissioned and the PR wasn't updated in a long time.
