### ISSUE TITLE
figure out how to identify failure due to wrong password

### ISSUE THREAD

**Issue by klrmn** [mozilla/bidpom#35]
i had some tests fail because i used the wrong password, the screenshot was as if sign in had never been pressed, because we automatically close the popup window rather than waiting for it to close on it's own.

the notification in the popup that explains the issue is only visible for max 2 seconds, making it hard to catch with selenium

@davehunt, i have an untested stash with changes that looks for the popup window by name rather than title, as well as waiting for the popup window to close rather than closing it forcefully.

**Comment by rbillings** [comment]
Currently the "Password Incorrect" error continues to display- but that wouldn't help if the window is being closed.
@klrmn is this still happening? What are your thoughts since it's been quite a while since the original issue was opened.

**Comment by davehunt** [comment]
Does #94 address this?

**Comment by davehunt** [comment]
Closing due to Persona (BrowserID) going away later this year.
