### ISSUE TITLE
Change user during test run.

### ISSUE THREAD

**Issue by bitgeeky** [mozilla/bidpom#82]
After the first user logs out, and second(different user) tries to login, persona doesn't prompts for a new email and password. Instead it uses the credentials(email+password) of the old user.
It makes it impossible to change user during test run.

Is there any option to deal with this kind of an issue ?
Thanks !!

**Comment by rbillings** [comment]
Hi - I am unable to repro this issue. If, for example, I sign in using Persona on One and Done and then log out- when I click the sign in button the Persona log in appears and I have the choice of returning as the same user or entering another email address. I believe this is standard. Are you still seeing this?

**Comment by davehunt** [comment]
This sounds like the expected behaviour. If there is a test that is blocked because BIDPOM is not providing suitable helpers for switching a user please reference it and reopen this issue.
