### ISSUE TITLE
Investigate potentially removing test_sign_in_is_this_your_computer

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bidpom#87]
test_sign_in_is_this_your_computer still runs (and takes around 90 seconds), even though it's xfailed with a Persona GitHub Issue that's been resolved, and most work nowadays is around Firefox Accounts.

Anybody have a good reason why we should keep this test around?

(At the least, if we're unsure, we should/could skip, rather than run.)

**Comment by stephendonner** [comment]
https://github.com/mozilla/bidpom/blob/master/tests/check_sign_in.py#L80 is the test

https://github.com/mozilla/persona/issues/4125 is the Persona issue

**Comment by rbillings** [comment]
The Persona issue is closed however the last comment was from November 2014 stating that the issue still occurs on staging. There was no fix submitted, only a previous comment that they were unable to repro the problem. It seems very unlikely that this will get fixed. 

I can't speak to how valuable the test is, but it's been out of circulation for over a year which makes me think it could be removed completely.

**Comment by bobsilverberg** [comment]
I agree, @rbillings, and have opened https://github.com/mozilla/bidpom/pull/95 to remove the test.
