### ISSUE TITLE
Investigate intermittent in test_sign_in_helper_with_returning_user

### ISSUE THREAD

**Issue by stephendonner** [mozilla/bidpom#89]
Investigate/file bug on or fix https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/72/

https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/72/testReport/junit/tests.check_sign_in/TestSignIn/test_sign_in_helper_with_returning_user/history/ is becoming more unreliable, for whatever reason(s)

@davehunt feel free to grab this one and/or delegate further :-)

**Comment by davehunt** [comment]
It looks like this test was failing for a while but improved. The most recent failure does not look related. I found two recent failures that look similar - they end up as timeouts on Sauce Labs (no new commands) and timeout locally (test running for 5 minutes). What's strange is that the things the commands they're waiting on don't appear to have been received by Sauce Labs. I'm going to leave this open for now to gather more information, but this could be a network issue if we're sending commands to Sauce that are never received. At very least we should be timing out sooner.

**Comment by davehunt** [comment]
See https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/72/testReport/junit/tests.check_sign_in/TestSignIn/test_sign_in_helper_with_returning_user/ and https://webqa-ci.mozilla.com/job/bidpom.stage.saucelabs/66/testReport/junit/tests.check_add_email/TestAddEmail/test_add_email/ for the recent failures of this type.

**Comment by rbillings** [comment]
It looks like the last failure for the test_sign_in_helper_with_returning_user was May 19th, and was from a timeout.

**Comment by bobsilverberg** [comment]
I think we can safely close this.
